//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.23 at 08:27:25 PM CST 
//


package com.transaction.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TRANSACTIONMANAGER }
     * 
     */
    public TRANSACTIONMANAGER createTRANSACTIONMANAGER() {
        return new TRANSACTIONMANAGER();
    }

    /**
     * Create an instance of {@link TRANSACTIONMANAGER.SOURCE }
     * 
     */
    public TRANSACTIONMANAGER.SOURCE createTRANSACTIONMANAGERSOURCE() {
        return new TRANSACTIONMANAGER.SOURCE();
    }

    /**
     * Create an instance of {@link TRANSACTIONMANAGER.PROPERTY }
     * 
     */
    public TRANSACTIONMANAGER.PROPERTY createTRANSACTIONMANAGERPROPERTY() {
        return new TRANSACTIONMANAGER.PROPERTY();
    }

    /**
     * Create an instance of {@link TRANSACTIONMANAGER.DATASOURCE }
     * 
     */
    public TRANSACTIONMANAGER.DATASOURCE createTRANSACTIONMANAGERDATASOURCE() {
        return new TRANSACTIONMANAGER.DATASOURCE();
    }

    /**
     * Create an instance of {@link TRANSACTIONMANAGER.SOURCE.METADATA }
     * 
     */
    public TRANSACTIONMANAGER.SOURCE.METADATA createTRANSACTIONMANAGERSOURCEMETADATA() {
        return new TRANSACTIONMANAGER.SOURCE.METADATA();
    }

    /**
     * Create an instance of {@link TRANSACTIONMANAGER.SOURCE.PARAMETER }
     * 
     */
    public TRANSACTIONMANAGER.SOURCE.PARAMETER createTRANSACTIONMANAGERSOURCEPARAMETER() {
        return new TRANSACTIONMANAGER.SOURCE.PARAMETER();
    }

}
