//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.23 at 08:27:25 PM CST 
//


package com.transaction.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SOURCE" maxOccurs="5000" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="METADATA" maxOccurs="5000" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="SOURCE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="COLNAME" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="SOURCEPARENT" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="COLNAMEPARENT" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="ORDER_ID" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="SQLTYPE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="PARAMETER" maxOccurs="5000" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="SOURCE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="PARAMETER" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="ID_ORDER" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="TYPE">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;enumeration value="DIRECT"/>
 *                                 &lt;enumeration value="PROPERTY"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="SQLTYPE">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;enumeration value="VARCHAR"/>
 *                                 &lt;enumeration value="LONGVARCHAR"/>
 *                                 &lt;enumeration value="NUMERIC"/>
 *                                 &lt;enumeration value="DECIMAL"/>
 *                                 &lt;enumeration value="BIT"/>
 *                                 &lt;enumeration value="TINYINT"/>
 *                                 &lt;enumeration value="SMALLINT"/>
 *                                 &lt;enumeration value="INTEGER"/>
 *                                 &lt;enumeration value="BIGINT"/>
 *                                 &lt;enumeration value="REAL"/>
 *                                 &lt;enumeration value="FLOAT"/>
 *                                 &lt;enumeration value="DOUBLE"/>
 *                                 &lt;enumeration value="BINARY"/>
 *                                 &lt;enumeration value="VARBINARY"/>
 *                                 &lt;enumeration value="LONGVARBINARY"/>
 *                                 &lt;enumeration value="DATE"/>
 *                                 &lt;enumeration value="TIME"/>
 *                                 &lt;enumeration value="TIMESTAMP"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="IS_MULTIVALUE">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;enumeration value="YES"/>
 *                                 &lt;enumeration value="NO"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="VALUE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="SOURCE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="SOURCEPARENT" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="GROUP" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="NAME" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="DIRECTION">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="INPUT"/>
 *                       &lt;enumeration value="OUPUT"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="TYPESOURCE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="FILENAME" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="PATH" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="CODINGFORMAT" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="HEADER">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="N/A"/>
 *                       &lt;enumeration value="YES"/>
 *                       &lt;enumeration value="NO"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="DELIMITER" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="LEFT_ENCLOSURE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="RIGHT_ENCLOUSURE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="SHEET_NAME" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="DATASOURCE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="SCRIPTSQL" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PROPERTY" maxOccurs="5000" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="PROPERTY" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="PROPERTY_PARENT" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="CATEGORY" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="SQLTYPE">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="VARCHAR"/>
 *                       &lt;enumeration value="LONGVARCHAR"/>
 *                       &lt;enumeration value="NUMERIC"/>
 *                       &lt;enumeration value="DECIMAL"/>
 *                       &lt;enumeration value="BIT"/>
 *                       &lt;enumeration value="TINYINT"/>
 *                       &lt;enumeration value="SMALLINT"/>
 *                       &lt;enumeration value="INTEGER"/>
 *                       &lt;enumeration value="BIGINT"/>
 *                       &lt;enumeration value="REAL"/>
 *                       &lt;enumeration value="FLOAT"/>
 *                       &lt;enumeration value="DOUBLE"/>
 *                       &lt;enumeration value="BINARY"/>
 *                       &lt;enumeration value="VARBINARY"/>
 *                       &lt;enumeration value="LONGVARBINARY"/>
 *                       &lt;enumeration value="DATE"/>
 *                       &lt;enumeration value="TIME"/>
 *                       &lt;enumeration value="TIMESTAMP"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="TYPE">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="DIRECT"/>
 *                       &lt;enumeration value="SQLVALUE"/>
 *                       &lt;enumeration value="SYSTEM"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="DATASOURCE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="IS_MULTIVALUE">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="YES"/>
 *                       &lt;enumeration value="NO"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="VALUE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DATASOURCE" maxOccurs="5000" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="DATASOURCE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="NAME" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="URL" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="USER" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="PASSWORD" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="DRIVERCLASSNAME" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="VALIDATION_QUERY" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "source",
    "property",
    "datasource"
})
@XmlRootElement(name = "TRANSACTIONMANAGER")
public class TRANSACTIONMANAGER {

    @XmlElement(name = "SOURCE")
    protected List<TRANSACTIONMANAGER.SOURCE> source;
    @XmlElement(name = "PROPERTY")
    protected List<TRANSACTIONMANAGER.PROPERTY> property;
    @XmlElement(name = "DATASOURCE")
    protected List<TRANSACTIONMANAGER.DATASOURCE> datasource;

    /**
     * Gets the value of the source property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the source property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSOURCE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRANSACTIONMANAGER.SOURCE }
     * 
     * 
     */
    public List<TRANSACTIONMANAGER.SOURCE> getSOURCE() {
        if (source == null) {
            source = new ArrayList<TRANSACTIONMANAGER.SOURCE>();
        }
        return this.source;
    }

    /**
     * Gets the value of the property property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPROPERTY().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRANSACTIONMANAGER.PROPERTY }
     * 
     * 
     */
    public List<TRANSACTIONMANAGER.PROPERTY> getPROPERTY() {
        if (property == null) {
            property = new ArrayList<TRANSACTIONMANAGER.PROPERTY>();
        }
        return this.property;
    }

    /**
     * Gets the value of the datasource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the datasource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDATASOURCE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRANSACTIONMANAGER.DATASOURCE }
     * 
     * 
     */
    public List<TRANSACTIONMANAGER.DATASOURCE> getDATASOURCE() {
        if (datasource == null) {
            datasource = new ArrayList<TRANSACTIONMANAGER.DATASOURCE>();
        }
        return this.datasource;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="DATASOURCE" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="NAME" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="URL" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="USER" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="PASSWORD" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="DRIVERCLASSNAME" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="VALIDATION_QUERY" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class DATASOURCE {

        @XmlAttribute(name = "DATASOURCE")
        protected String datasource;
        @XmlAttribute(name = "NAME")
        protected String name;
        @XmlAttribute(name = "URL")
        protected String url;
        @XmlAttribute(name = "USER")
        protected String user;
        @XmlAttribute(name = "PASSWORD")
        protected String password;
        @XmlAttribute(name = "DRIVERCLASSNAME")
        protected String driverclassname;
        @XmlAttribute(name = "VALIDATION_QUERY")
        protected String validationquery;

        /**
         * Gets the value of the datasource property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDATASOURCE() {
            return datasource;
        }

        /**
         * Sets the value of the datasource property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDATASOURCE(String value) {
            this.datasource = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNAME() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNAME(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the url property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getURL() {
            return url;
        }

        /**
         * Sets the value of the url property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setURL(String value) {
            this.url = value;
        }

        /**
         * Gets the value of the user property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUSER() {
            return user;
        }

        /**
         * Sets the value of the user property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUSER(String value) {
            this.user = value;
        }

        /**
         * Gets the value of the password property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPASSWORD() {
            return password;
        }

        /**
         * Sets the value of the password property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPASSWORD(String value) {
            this.password = value;
        }

        /**
         * Gets the value of the driverclassname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDRIVERCLASSNAME() {
            return driverclassname;
        }

        /**
         * Sets the value of the driverclassname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDRIVERCLASSNAME(String value) {
            this.driverclassname = value;
        }

        /**
         * Gets the value of the validationquery property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVALIDATIONQUERY() {
            return validationquery;
        }

        /**
         * Sets the value of the validationquery property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVALIDATIONQUERY(String value) {
            this.validationquery = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="PROPERTY" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="PROPERTY_PARENT" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="CATEGORY" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="SQLTYPE">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="VARCHAR"/>
     *             &lt;enumeration value="LONGVARCHAR"/>
     *             &lt;enumeration value="NUMERIC"/>
     *             &lt;enumeration value="DECIMAL"/>
     *             &lt;enumeration value="BIT"/>
     *             &lt;enumeration value="TINYINT"/>
     *             &lt;enumeration value="SMALLINT"/>
     *             &lt;enumeration value="INTEGER"/>
     *             &lt;enumeration value="BIGINT"/>
     *             &lt;enumeration value="REAL"/>
     *             &lt;enumeration value="FLOAT"/>
     *             &lt;enumeration value="DOUBLE"/>
     *             &lt;enumeration value="BINARY"/>
     *             &lt;enumeration value="VARBINARY"/>
     *             &lt;enumeration value="LONGVARBINARY"/>
     *             &lt;enumeration value="DATE"/>
     *             &lt;enumeration value="TIME"/>
     *             &lt;enumeration value="TIMESTAMP"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="TYPE">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="DIRECT"/>
     *             &lt;enumeration value="SQLVALUE"/>
     *             &lt;enumeration value="SYSTEM"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="DATASOURCE" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="IS_MULTIVALUE">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="YES"/>
     *             &lt;enumeration value="NO"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="VALUE" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class PROPERTY {

        @XmlAttribute(name = "PROPERTY")
        protected String property;
        @XmlAttribute(name = "PROPERTY_PARENT")
        protected String propertyparent;
        @XmlAttribute(name = "CATEGORY")
        protected String category;
        @XmlAttribute(name = "SQLTYPE")
        protected String sqltype;
        @XmlAttribute(name = "TYPE")
        protected String type;
        @XmlAttribute(name = "DATASOURCE")
        protected String datasource;
        @XmlAttribute(name = "IS_MULTIVALUE")
        protected String ismultivalue;
        @XmlAttribute(name = "VALUE")
        protected String value;

        /**
         * Gets the value of the property property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPROPERTY() {
            return property;
        }

        /**
         * Sets the value of the property property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPROPERTY(String value) {
            this.property = value;
        }

        /**
         * Gets the value of the propertyparent property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPROPERTYPARENT() {
            return propertyparent;
        }

        /**
         * Sets the value of the propertyparent property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPROPERTYPARENT(String value) {
            this.propertyparent = value;
        }

        /**
         * Gets the value of the category property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCATEGORY() {
            return category;
        }

        /**
         * Sets the value of the category property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCATEGORY(String value) {
            this.category = value;
        }

        /**
         * Gets the value of the sqltype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSQLTYPE() {
            return sqltype;
        }

        /**
         * Sets the value of the sqltype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSQLTYPE(String value) {
            this.sqltype = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTYPE() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTYPE(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the datasource property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDATASOURCE() {
            return datasource;
        }

        /**
         * Sets the value of the datasource property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDATASOURCE(String value) {
            this.datasource = value;
        }

        /**
         * Gets the value of the ismultivalue property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getISMULTIVALUE() {
            return ismultivalue;
        }

        /**
         * Sets the value of the ismultivalue property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setISMULTIVALUE(String value) {
            this.ismultivalue = value;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVALUE() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVALUE(String value) {
            this.value = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="METADATA" maxOccurs="5000" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="SOURCE" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="COLNAME" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="SOURCEPARENT" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="COLNAMEPARENT" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="ORDER_ID" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="SQLTYPE" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="PARAMETER" maxOccurs="5000" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="SOURCE" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="PARAMETER" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="ID_ORDER" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="TYPE">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;enumeration value="DIRECT"/>
     *                       &lt;enumeration value="PROPERTY"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="SQLTYPE">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;enumeration value="VARCHAR"/>
     *                       &lt;enumeration value="LONGVARCHAR"/>
     *                       &lt;enumeration value="NUMERIC"/>
     *                       &lt;enumeration value="DECIMAL"/>
     *                       &lt;enumeration value="BIT"/>
     *                       &lt;enumeration value="TINYINT"/>
     *                       &lt;enumeration value="SMALLINT"/>
     *                       &lt;enumeration value="INTEGER"/>
     *                       &lt;enumeration value="BIGINT"/>
     *                       &lt;enumeration value="REAL"/>
     *                       &lt;enumeration value="FLOAT"/>
     *                       &lt;enumeration value="DOUBLE"/>
     *                       &lt;enumeration value="BINARY"/>
     *                       &lt;enumeration value="VARBINARY"/>
     *                       &lt;enumeration value="LONGVARBINARY"/>
     *                       &lt;enumeration value="DATE"/>
     *                       &lt;enumeration value="TIME"/>
     *                       &lt;enumeration value="TIMESTAMP"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="IS_MULTIVALUE">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;enumeration value="YES"/>
     *                       &lt;enumeration value="NO"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="VALUE" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="SOURCE" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="SOURCEPARENT" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="GROUP" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="NAME" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="DIRECTION">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="INPUT"/>
     *             &lt;enumeration value="OUPUT"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="TYPESOURCE" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="FILENAME" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="PATH" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="CODINGFORMAT" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="HEADER">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="N/A"/>
     *             &lt;enumeration value="YES"/>
     *             &lt;enumeration value="NO"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="DELIMITER" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="LEFT_ENCLOSURE" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="RIGHT_ENCLOUSURE" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="SHEET_NAME" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="DATASOURCE" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="SCRIPTSQL" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "metadata",
        "parameter"
    })
    public static class SOURCE {

        @XmlElement(name = "METADATA")
        protected List<TRANSACTIONMANAGER.SOURCE.METADATA> metadata;
        @XmlElement(name = "PARAMETER")
        protected List<TRANSACTIONMANAGER.SOURCE.PARAMETER> parameter;
        @XmlAttribute(name = "SOURCE")
        protected String source;
        @XmlAttribute(name = "SOURCEPARENT")
        protected String sourceparent;
        @XmlAttribute(name = "GROUP")
        protected String group;
        @XmlAttribute(name = "NAME")
        protected String name;
        @XmlAttribute(name = "DIRECTION")
        protected String direction;
        @XmlAttribute(name = "TYPESOURCE")
        protected String typesource;
        @XmlAttribute(name = "FILENAME")
        protected String filename;
        @XmlAttribute(name = "PATH")
        protected String path;
        @XmlAttribute(name = "CODINGFORMAT")
        protected String codingformat;
        @XmlAttribute(name = "HEADER")
        protected String header;
        @XmlAttribute(name = "DELIMITER")
        protected String delimiter;
        @XmlAttribute(name = "LEFT_ENCLOSURE")
        protected String leftenclosure;
        @XmlAttribute(name = "RIGHT_ENCLOUSURE")
        protected String rightenclousure;
        @XmlAttribute(name = "SHEET_NAME")
        protected String sheetname;
        @XmlAttribute(name = "DATASOURCE")
        protected String datasource;
        @XmlAttribute(name = "SCRIPTSQL")
        protected String scriptsql;

        /**
         * Gets the value of the metadata property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the metadata property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMETADATA().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TRANSACTIONMANAGER.SOURCE.METADATA }
         * 
         * 
         */
        public List<TRANSACTIONMANAGER.SOURCE.METADATA> getMETADATA() {
            if (metadata == null) {
                metadata = new ArrayList<TRANSACTIONMANAGER.SOURCE.METADATA>();
            }
            return this.metadata;
        }

        /**
         * Gets the value of the parameter property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the parameter property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPARAMETER().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TRANSACTIONMANAGER.SOURCE.PARAMETER }
         * 
         * 
         */
        public List<TRANSACTIONMANAGER.SOURCE.PARAMETER> getPARAMETER() {
            if (parameter == null) {
                parameter = new ArrayList<TRANSACTIONMANAGER.SOURCE.PARAMETER>();
            }
            return this.parameter;
        }

        /**
         * Gets the value of the source property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSOURCE() {
            return source;
        }

        /**
         * Sets the value of the source property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSOURCE(String value) {
            this.source = value;
        }

        /**
         * Gets the value of the sourceparent property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSOURCEPARENT() {
            return sourceparent;
        }

        /**
         * Sets the value of the sourceparent property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSOURCEPARENT(String value) {
            this.sourceparent = value;
        }

        /**
         * Gets the value of the group property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGROUP() {
            return group;
        }

        /**
         * Sets the value of the group property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGROUP(String value) {
            this.group = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNAME() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNAME(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the direction property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDIRECTION() {
            return direction;
        }

        /**
         * Sets the value of the direction property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDIRECTION(String value) {
            this.direction = value;
        }

        /**
         * Gets the value of the typesource property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTYPESOURCE() {
            return typesource;
        }

        /**
         * Sets the value of the typesource property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTYPESOURCE(String value) {
            this.typesource = value;
        }

        /**
         * Gets the value of the filename property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFILENAME() {
            return filename;
        }

        /**
         * Sets the value of the filename property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFILENAME(String value) {
            this.filename = value;
        }

        /**
         * Gets the value of the path property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPATH() {
            return path;
        }

        /**
         * Sets the value of the path property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPATH(String value) {
            this.path = value;
        }

        /**
         * Gets the value of the codingformat property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCODINGFORMAT() {
            return codingformat;
        }

        /**
         * Sets the value of the codingformat property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCODINGFORMAT(String value) {
            this.codingformat = value;
        }

        /**
         * Gets the value of the header property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHEADER() {
            return header;
        }

        /**
         * Sets the value of the header property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHEADER(String value) {
            this.header = value;
        }

        /**
         * Gets the value of the delimiter property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDELIMITER() {
            return delimiter;
        }

        /**
         * Sets the value of the delimiter property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDELIMITER(String value) {
            this.delimiter = value;
        }

        /**
         * Gets the value of the leftenclosure property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLEFTENCLOSURE() {
            return leftenclosure;
        }

        /**
         * Sets the value of the leftenclosure property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLEFTENCLOSURE(String value) {
            this.leftenclosure = value;
        }

        /**
         * Gets the value of the rightenclousure property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRIGHTENCLOUSURE() {
            return rightenclousure;
        }

        /**
         * Sets the value of the rightenclousure property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRIGHTENCLOUSURE(String value) {
            this.rightenclousure = value;
        }

        /**
         * Gets the value of the sheetname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSHEETNAME() {
            return sheetname;
        }

        /**
         * Sets the value of the sheetname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSHEETNAME(String value) {
            this.sheetname = value;
        }

        /**
         * Gets the value of the datasource property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDATASOURCE() {
            return datasource;
        }

        /**
         * Sets the value of the datasource property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDATASOURCE(String value) {
            this.datasource = value;
        }

        /**
         * Gets the value of the scriptsql property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSCRIPTSQL() {
            return scriptsql;
        }

        /**
         * Sets the value of the scriptsql property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSCRIPTSQL(String value) {
            this.scriptsql = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="SOURCE" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="COLNAME" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="SOURCEPARENT" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="COLNAMEPARENT" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="ORDER_ID" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="SQLTYPE" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class METADATA {

            @XmlAttribute(name = "SOURCE")
            protected String source;
            @XmlAttribute(name = "COLNAME")
            protected String colname;
            @XmlAttribute(name = "SOURCEPARENT")
            protected String sourceparent;
            @XmlAttribute(name = "COLNAMEPARENT")
            protected String colnameparent;
            @XmlAttribute(name = "ORDER_ID")
            protected Integer orderid;
            @XmlAttribute(name = "SQLTYPE")
            protected String sqltype;

            /**
             * Gets the value of the source property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSOURCE() {
                return source;
            }

            /**
             * Sets the value of the source property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSOURCE(String value) {
                this.source = value;
            }

            /**
             * Gets the value of the colname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCOLNAME() {
                return colname;
            }

            /**
             * Sets the value of the colname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCOLNAME(String value) {
                this.colname = value;
            }

            /**
             * Gets the value of the sourceparent property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSOURCEPARENT() {
                return sourceparent;
            }

            /**
             * Sets the value of the sourceparent property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSOURCEPARENT(String value) {
                this.sourceparent = value;
            }

            /**
             * Gets the value of the colnameparent property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCOLNAMEPARENT() {
                return colnameparent;
            }

            /**
             * Sets the value of the colnameparent property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCOLNAMEPARENT(String value) {
                this.colnameparent = value;
            }

            /**
             * Gets the value of the orderid property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getORDERID() {
                return orderid;
            }

            /**
             * Sets the value of the orderid property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setORDERID(Integer value) {
                this.orderid = value;
            }

            /**
             * Gets the value of the sqltype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSQLTYPE() {
                return sqltype;
            }

            /**
             * Sets the value of the sqltype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSQLTYPE(String value) {
                this.sqltype = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="SOURCE" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="PARAMETER" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="ID_ORDER" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="TYPE">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="DIRECT"/>
         *             &lt;enumeration value="PROPERTY"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="SQLTYPE">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="VARCHAR"/>
         *             &lt;enumeration value="LONGVARCHAR"/>
         *             &lt;enumeration value="NUMERIC"/>
         *             &lt;enumeration value="DECIMAL"/>
         *             &lt;enumeration value="BIT"/>
         *             &lt;enumeration value="TINYINT"/>
         *             &lt;enumeration value="SMALLINT"/>
         *             &lt;enumeration value="INTEGER"/>
         *             &lt;enumeration value="BIGINT"/>
         *             &lt;enumeration value="REAL"/>
         *             &lt;enumeration value="FLOAT"/>
         *             &lt;enumeration value="DOUBLE"/>
         *             &lt;enumeration value="BINARY"/>
         *             &lt;enumeration value="VARBINARY"/>
         *             &lt;enumeration value="LONGVARBINARY"/>
         *             &lt;enumeration value="DATE"/>
         *             &lt;enumeration value="TIME"/>
         *             &lt;enumeration value="TIMESTAMP"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="IS_MULTIVALUE">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="YES"/>
         *             &lt;enumeration value="NO"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="VALUE" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class PARAMETER {

            @XmlAttribute(name = "SOURCE")
            protected String source;
            @XmlAttribute(name = "PARAMETER")
            protected String parameter;
            @XmlAttribute(name = "ID_ORDER")
            protected Integer idorder;
            @XmlAttribute(name = "TYPE")
            protected String type;
            @XmlAttribute(name = "SQLTYPE")
            protected String sqltype;
            @XmlAttribute(name = "IS_MULTIVALUE")
            protected String ismultivalue;
            @XmlAttribute(name = "VALUE")
            protected String value;

            /**
             * Gets the value of the source property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSOURCE() {
                return source;
            }

            /**
             * Sets the value of the source property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSOURCE(String value) {
                this.source = value;
            }

            /**
             * Gets the value of the parameter property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPARAMETER() {
                return parameter;
            }

            /**
             * Sets the value of the parameter property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPARAMETER(String value) {
                this.parameter = value;
            }

            /**
             * Gets the value of the idorder property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getIDORDER() {
                return idorder;
            }

            /**
             * Sets the value of the idorder property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setIDORDER(Integer value) {
                this.idorder = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTYPE() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTYPE(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the sqltype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSQLTYPE() {
                return sqltype;
            }

            /**
             * Sets the value of the sqltype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSQLTYPE(String value) {
                this.sqltype = value;
            }

            /**
             * Gets the value of the ismultivalue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getISMULTIVALUE() {
                return ismultivalue;
            }

            /**
             * Sets the value of the ismultivalue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setISMULTIVALUE(String value) {
                this.ismultivalue = value;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVALUE() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVALUE(String value) {
                this.value = value;
            }

        }

    }

}
